// Quiz templates. Math templates are generated by code, so the right answer is always right;
// "video" templates are written by the model from the transcript and only checked here.
// Every template makes items that match schemas/quiz-item.schema.json.

const EN = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'];
const RU = ['ноль', 'один', 'два', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять', 'десять',
  'одиннадцать', 'двенадцать', 'тринадцать', 'четырнадцать', 'пятнадцать', 'шестнадцать', 'семнадцать', 'восемнадцать', 'девятнадцать', 'двадцать'];

const isRu = (lang) => String(lang ?? '').startsWith('ru');
const numberAnswers = (n) => [String(n), EN[n], RU[n]].filter(Boolean);
const int = (x, min, max, dflt) => (Number.isInteger(x) && x >= min && x <= max ? x : dflt);

// rng: () => [0, 1). Tests pass a fixed one.
const pick = (rng, lo, hi) => lo + Math.floor(rng() * (hi - lo + 1));

function voice(prompt, accept, lang) {
  return { type: 'voice', prompt, answer: { kind: 'text', accept }, ...(lang ? { lang } : {}) };
}

export const TEMPLATES = {
  add: {
    title: 'Adding', skill: 'math: plus', answer: 'voice',
    howItWorks: 'Two numbers that add up to at most `max`. He says the answer.',
    params: { max: 'largest answer, 3 to 20 (default 10)' },
    example: 'What is 3 plus 4? → 7',
    make({ max } = {}, lang, rng) {
      const m = int(max, 2, 20, 10);
      const a = pick(rng, 1, m - 1), b = pick(rng, 1, m - a);
      return { id: `add-${a}-${b}`, item: voice(isRu(lang) ? `Сколько будет ${a} плюс ${b}?` : `What is ${a} plus ${b}?`, numberAnswers(a + b), lang) };
    },
  },
  subtract: {
    title: 'Taking away', skill: 'math: minus', answer: 'voice',
    howItWorks: 'A number up to `max` minus a smaller one. He says the answer.',
    params: { max: 'largest starting number, 3 to 20 (default 10)' },
    example: 'What is 7 minus 2? → 5',
    make({ max } = {}, lang, rng) {
      const m = int(max, 2, 20, 10);
      const a = pick(rng, 2, m), b = pick(rng, 1, a - 1);
      return { id: `sub-${a}-${b}`, item: voice(isRu(lang) ? `Сколько будет ${a} минус ${b}?` : `What is ${a} minus ${b}?`, numberAnswers(a - b), lang) };
    },
  },
  'next-number': {
    title: 'What comes next', skill: 'math: counting', answer: 'voice',
    howItWorks: 'A number up to `max`; he says the one after it.',
    params: { max: 'largest answer, 3 to 20 (default 10)' },
    example: 'What number comes after 6? → 7',
    make({ max } = {}, lang, rng) {
      const n = pick(rng, 1, int(max, 2, 20, 10) - 1);
      return { id: `next-${n}`, item: voice(isRu(lang) ? `Какое число идёт после ${n}?` : `What number comes after ${n}?`, numberAnswers(n + 1), lang) };
    },
  },
  'number-before': {
    title: 'What comes before', skill: 'math: counting', answer: 'voice',
    howItWorks: 'A number up to `max`; he says the one before it.',
    params: { max: 'largest number, 3 to 20 (default 10)' },
    example: 'What number comes before 5? → 4',
    make({ max } = {}, lang, rng) {
      const n = pick(rng, 2, int(max, 2, 20, 10));
      return { id: `before-${n}`, item: voice(isRu(lang) ? `Какое число идёт перед ${n}?` : `What number comes before ${n}?`, numberAnswers(n - 1), lang) };
    },
  },
  bigger: {
    title: 'Which is bigger', skill: 'math: comparing', answer: 'choice',
    howItWorks: 'Two different numbers up to `max`; he taps the bigger one.',
    params: { max: 'largest number, 3 to 20 (default 10)' },
    example: 'Which is bigger: 4 or 7? → 7',
    make({ max } = {}, lang, rng) {
      const m = int(max, 2, 20, 10);
      const a = pick(rng, 1, m);
      let b = pick(rng, 1, m - 1);
      if (b >= a) b++;
      return {
        id: `bigger-${Math.min(a, b)}-${Math.max(a, b)}`,
        item: { type: 'choice', prompt: isRu(lang) ? `Какое число больше: ${a} или ${b}?` : `Which is bigger: ${a} or ${b}?`,
          answer: { kind: 'choice', options: [String(a), String(b)], correct: String(Math.max(a, b)) }, ...(lang ? { lang } : {}) },
      };
    },
  },
  'video-voice': {
    title: 'Say it: about the video', skill: 'remembering the video', answer: 'voice',
    howItWorks: 'A question about something the video clearly says. He says a one- or two-word answer.',
    params: { prompt: 'the question, short and spoken', accept: 'answers that count, short, include synonyms and digits/words' },
    example: 'How many legs does a spider have? → eight / 8',
    make({ prompt, accept } = {}, lang) {
      const acc = [...new Set((Array.isArray(accept) ? accept : []).map((a) => String(a).trim()).filter((a) => a && a.length <= 40))];
      if (!prompt || !acc.length) return null;
      for (const a of [...acc]) { const n = EN.indexOf(a.toLowerCase()) >= 0 ? EN.indexOf(a.toLowerCase()) : RU.indexOf(a.toLowerCase()) >= 0 ? RU.indexOf(a.toLowerCase()) : /^\d+$/.test(a) ? Number(a) : -1; if (n >= 0 && n <= 20) acc.push(...numberAnswers(n)); }
      return { item: voice(String(prompt).slice(0, 300), [...new Set(acc)], lang) };
    },
  },
  'video-choice': {
    title: 'Tap it: about the video', skill: 'remembering the video', answer: 'choice',
    howItWorks: 'A question about the video with 2–3 picture-free options; he taps one.',
    params: { prompt: 'the question', options: '2 or 3 short options', correct: 'the right option, exactly as written' },
    example: 'What do bees make? honey / milk / bread',
    make({ prompt, options, correct } = {}, lang) {
      const opts = [...new Set((Array.isArray(options) ? options : []).map((o) => String(o).trim()).filter(Boolean))].slice(0, 4);
      if (!prompt || opts.length < 2 || !opts.includes(String(correct).trim())) return null;
      return { item: { type: 'choice', prompt: String(prompt).slice(0, 300), answer: { kind: 'choice', options: opts, correct: String(correct).trim() }, ...(lang ? { lang } : {}) } };
    },
  },
};

// A short stable id piece from a video id (video ids have capitals and "_", quiz ids can't).
export function videoKey(videoId) {
  let h = 0;
  for (const c of videoId) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return h.toString(36);
}

// specs: [{ template, params, count? }] from the model
// (those are written by the model as video-voice / video-choice). Returns { items: {id: item}, ids }.
export function buildQuiz(videoId, specs, lang, { rng = Math.random, max = 3 } = {}) {
  const items = {};
  const ids = [];
  let n = 0;
  for (const spec of Array.isArray(specs) ? specs : []) {
    const t = TEMPLATES[spec?.template];
    if (!t) continue;
    for (let k = 0; k < Math.min(Number(spec.count) || 1, 3) && ids.length < max; k++) {
      const made = t.make(spec.params ?? spec, lang, rng);
      if (!made) break;
      const id = made.id ?? `v-${videoKey(videoId)}-${++n}`;
      if (items[id]) continue;
      items[id] = made.item;
      ids.push(id);
    }
  }
  return { items, ids };
}

// For the prompt (the question types the helper may use).
export function templateCatalog() {
  return Object.entries(TEMPLATES).map(([id, t]) => ({ id, title: t.title, skill: t.skill, answer: t.answer, howItWorks: t.howItWorks, params: t.params, example: t.example }));
}
